DROP TABLE IF EXISTS imiona;
CREATE TABLE IF NOT EXISTS imiona(
 idi INTEGER PRIMARY KEY,
 imie TEXT UNIQUE,
 pozycja INT,
 liczba INT,
 plec CHAR(1));
BEGIN TRANSACTION;
INSERT INTO imiona(pozycja,imie) VALUES (1,'Anna');
INSERT INTO imiona(pozycja,imie) VALUES (1,'Piotr');
INSERT INTO imiona(pozycja,imie) VALUES (2,'Maria');
INSERT INTO imiona(pozycja,imie) VALUES (2,'Krzysztof');
INSERT INTO imiona(pozycja,imie) VALUES (3,'Katarzyna');
INSERT INTO imiona(pozycja,imie) VALUES (3,'Andrzej');
INSERT INTO imiona(pozycja,imie) VALUES (4,'Małgorzata');
INSERT INTO imiona(pozycja,imie) VALUES (4,'Jan');
INSERT INTO imiona(pozycja,imie) VALUES (5,'Agnieszka');
INSERT INTO imiona(pozycja,imie) VALUES (5,'Stanisław');
INSERT INTO imiona(pozycja,imie) VALUES (6,'Barbara');
INSERT INTO imiona(pozycja,imie) VALUES (6,'Tomasz');
INSERT INTO imiona(pozycja,imie) VALUES (7,'Krystyna');
INSERT INTO imiona(pozycja,imie) VALUES (7,'Paweł');
INSERT INTO imiona(pozycja,imie) VALUES (8,'Ewa');
INSERT INTO imiona(pozycja,imie) VALUES (8,'Marcin');
INSERT INTO imiona(pozycja,imie) VALUES (9,'Elżbieta');
INSERT INTO imiona(pozycja,imie) VALUES (9,'Michał');
INSERT INTO imiona(pozycja,imie) VALUES (10,'Zofia');
INSERT INTO imiona(pozycja,imie) VALUES (10,'Marek');
INSERT INTO imiona(pozycja,imie) VALUES (11,'Teresa');
INSERT INTO imiona(pozycja,imie) VALUES (11,'Grzegorz');
INSERT INTO imiona(pozycja,imie) VALUES (12,'Magdalena');
INSERT INTO imiona(pozycja,imie) VALUES (12,'Józef');
INSERT INTO imiona(pozycja,imie) VALUES (13,'Joanna');
INSERT INTO imiona(pozycja,imie) VALUES (13,'Łukasz');
INSERT INTO imiona(pozycja,imie) VALUES (14,'Janina');
INSERT INTO imiona(pozycja,imie) VALUES (14,'Adam');
INSERT INTO imiona(pozycja,imie) VALUES (15,'Monika');
INSERT INTO imiona(pozycja,imie) VALUES (15,'Zbigniew');
INSERT INTO imiona(pozycja,imie) VALUES (16,'Danuta');
INSERT INTO imiona(pozycja,imie) VALUES (16,'Jerzy');
INSERT INTO imiona(pozycja,imie) VALUES (17,'Jadwiga');
INSERT INTO imiona(pozycja,imie) VALUES (17,'Tadeusz');
INSERT INTO imiona(pozycja,imie) VALUES (18,'Aleksandra');
INSERT INTO imiona(pozycja,imie) VALUES (18,'Mateusz');
INSERT INTO imiona(pozycja,imie) VALUES (19,'Halina');
INSERT INTO imiona(pozycja,imie) VALUES (19,'Dariusz');
INSERT INTO imiona(pozycja,imie) VALUES (20,'Irena');
INSERT INTO imiona(pozycja,imie) VALUES (20,'Mariusz');
INSERT INTO imiona(pozycja,imie) VALUES (21,'Beata');
INSERT INTO imiona(pozycja,imie) VALUES (21,'Wojciech');
INSERT INTO imiona(pozycja,imie) VALUES (22,'Marta');
INSERT INTO imiona(pozycja,imie) VALUES (22,'Ryszard');
INSERT INTO imiona(pozycja,imie) VALUES (23,'Dorota');
INSERT INTO imiona(pozycja,imie) VALUES (23,'Jakub');
INSERT INTO imiona(pozycja,imie) VALUES (24,'Helena');
INSERT INTO imiona(pozycja,imie) VALUES (24,'Henryk');
INSERT INTO imiona(pozycja,imie) VALUES (25,'Karolina');
INSERT INTO imiona(pozycja,imie) VALUES (25,'Robert');
INSERT INTO imiona(pozycja,imie) VALUES (26,'Grażyna');
INSERT INTO imiona(pozycja,imie) VALUES (26,'Rafał');
INSERT INTO imiona(pozycja,imie) VALUES (27,'Jolanta');
INSERT INTO imiona(pozycja,imie) VALUES (27,'Kazimierz');
INSERT INTO imiona(pozycja,imie) VALUES (28,'Iwona');
INSERT INTO imiona(pozycja,imie) VALUES (28,'Jacek');
INSERT INTO imiona(pozycja,imie) VALUES (29,'Marianna');
INSERT INTO imiona(pozycja,imie) VALUES (29,'Maciej');
INSERT INTO imiona(pozycja,imie) VALUES (30,'Natalia');
INSERT INTO imiona(pozycja,imie) VALUES (30,'Kamil');
INSERT INTO imiona(pozycja,imie) VALUES (31,'Bożena');
INSERT INTO imiona(pozycja,imie) VALUES (31,'Janusz');
INSERT INTO imiona(pozycja,imie) VALUES (32,'Stanisława');
INSERT INTO imiona(pozycja,imie) VALUES (32,'Marian');
INSERT INTO imiona(pozycja,imie) VALUES (33,'Justyna');
INSERT INTO imiona(pozycja,imie) VALUES (33,'Mirosław');
INSERT INTO imiona(pozycja,imie) VALUES (34,'Paulina');
INSERT INTO imiona(pozycja,imie) VALUES (34,'Jarosław');
INSERT INTO imiona(pozycja,imie) VALUES (35,'Urszula');
INSERT INTO imiona(pozycja,imie) VALUES (35,'Sławomir');
INSERT INTO imiona(pozycja,imie) VALUES (36,'Alicja');
INSERT INTO imiona(pozycja,imie) VALUES (36,'Dawid');
INSERT INTO imiona(pozycja,imie) VALUES (37,'Renata');
INSERT INTO imiona(pozycja,imie) VALUES (37,'Wiesław');
INSERT INTO imiona(pozycja,imie) VALUES (38,'Sylwia');
INSERT INTO imiona(pozycja,imie) VALUES (38,'Artur');
INSERT INTO imiona(pozycja,imie) VALUES (39,'Agata');
INSERT INTO imiona(pozycja,imie) VALUES (39,'Roman');
INSERT INTO imiona(pozycja,imie) VALUES (40,'Aneta');
INSERT INTO imiona(pozycja,imie) VALUES (40,'Damian');
INSERT INTO imiona(pozycja,imie) VALUES (41,'Patrycja');
INSERT INTO imiona(pozycja,imie) VALUES (41,'Przemysław');
INSERT INTO imiona(pozycja,imie) VALUES (42,'Izabela');
INSERT INTO imiona(pozycja,imie) VALUES (42,'Sebastian');
INSERT INTO imiona(pozycja,imie) VALUES (43,'Ewelina');
INSERT INTO imiona(pozycja,imie) VALUES (43,'Daniel');
INSERT INTO imiona(pozycja,imie) VALUES (44,'Julia');
INSERT INTO imiona(pozycja,imie) VALUES (44,'Władysław');
INSERT INTO imiona(pozycja,imie) VALUES (45,'Wanda');
INSERT INTO imiona(pozycja,imie) VALUES (45,'Zdzisław');
INSERT INTO imiona(pozycja,imie) VALUES (46,'Marzena');
INSERT INTO imiona(pozycja,imie) VALUES (46,'Patryk');
INSERT INTO imiona(pozycja,imie) VALUES (47,'Wiesława');
INSERT INTO imiona(pozycja,imie) VALUES (47,'Bartosz');
INSERT INTO imiona(pozycja,imie) VALUES (48,'Weronika');
INSERT INTO imiona(pozycja,imie) VALUES (48,'Edward');
INSERT INTO imiona(pozycja,imie) VALUES (49,'Wiktoria');
INSERT INTO imiona(pozycja,imie) VALUES (49,'Mieczysław');
INSERT INTO imiona(pozycja,imie) VALUES (50,'Klaudia');
INSERT INTO imiona(pozycja,imie) VALUES (50,'Leszek');
INSERT INTO imiona(pozycja,imie) VALUES (51,'Edyta');
INSERT INTO imiona(pozycja,imie) VALUES (51,'Karol');
INSERT INTO imiona(pozycja,imie) VALUES (52,'Emilia');
INSERT INTO imiona(pozycja,imie) VALUES (52,'Arkadiusz');
INSERT INTO imiona(pozycja,imie) VALUES (53,'Genowefa');
INSERT INTO imiona(pozycja,imie) VALUES (53,'Czesław');
INSERT INTO imiona(pozycja,imie) VALUES (54,'Dominika');
INSERT INTO imiona(pozycja,imie) VALUES (54,'Waldemar');
INSERT INTO imiona(pozycja,imie) VALUES (55,'Kazimiera');
INSERT INTO imiona(pozycja,imie) VALUES (55,'Szymon');
INSERT INTO imiona(pozycja,imie) VALUES (56,'Hanna');
INSERT INTO imiona(pozycja,imie) VALUES (56,'Adrian');
INSERT INTO imiona(pozycja,imie) VALUES (57,'Kamila');
INSERT INTO imiona(pozycja,imie) VALUES (57,'Kacper');
INSERT INTO imiona(pozycja,imie) VALUES (58,'Martyna');
INSERT INTO imiona(pozycja,imie) VALUES (58,'Bogdan');
INSERT INTO imiona(pozycja,imie) VALUES (59,'Kinga');
INSERT INTO imiona(pozycja,imie) VALUES (59,'Eugeniusz');
INSERT INTO imiona(pozycja,imie) VALUES (60,'Lucyna');
INSERT INTO imiona(pozycja,imie) VALUES (60,'Bartłomiej');
INSERT INTO imiona(pozycja,imie) VALUES (61,'Stefania');
INSERT INTO imiona(pozycja,imie) VALUES (61,'Antoni');
INSERT INTO imiona(pozycja,imie) VALUES (62,'Józefa');
INSERT INTO imiona(pozycja,imie) VALUES (62,'Franciszek');
INSERT INTO imiona(pozycja,imie) VALUES (63,'Alina');
INSERT INTO imiona(pozycja,imie) VALUES (63,'Stefan');
INSERT INTO imiona(pozycja,imie) VALUES (64,'Zuzanna');
INSERT INTO imiona(pozycja,imie) VALUES (64,'Radosław');
INSERT INTO imiona(pozycja,imie) VALUES (65,'Gabriela');
INSERT INTO imiona(pozycja,imie) VALUES (66,'Zygmunt');
INSERT INTO imiona(pozycja,imie) VALUES (66,'Władysława');
INSERT INTO imiona(pozycja,imie) VALUES (66,'Dominik');
INSERT INTO imiona(pozycja,imie) VALUES (67,'Mariola');
INSERT INTO imiona(pozycja,imie) VALUES (67,'Krystian');
INSERT INTO imiona(pozycja,imie) VALUES (68,'Lidia');
INSERT INTO imiona(pozycja,imie) VALUES (68,'Konrad');
INSERT INTO imiona(pozycja,imie) VALUES (69,'Mirosława');
INSERT INTO imiona(pozycja,imie) VALUES (69,'Aleksander');
INSERT INTO imiona(pozycja,imie) VALUES (70,'Henryka');
INSERT INTO imiona(pozycja,imie) VALUES (70,'Bogusław');
INSERT INTO imiona(pozycja,imie) VALUES (71,'Wioletta');
INSERT INTO imiona(pozycja,imie) VALUES (71,'Ireneusz');
INSERT INTO imiona(pozycja,imie) VALUES (72,'Czesława');
INSERT INTO imiona(pozycja,imie) VALUES (72,'Włodzimierz');
INSERT INTO imiona(pozycja,imie) VALUES (73,'Oliwia');
INSERT INTO imiona(pozycja,imie) VALUES (73,'Zenon');
INSERT INTO imiona(pozycja,imie) VALUES (74,'Regina');
INSERT INTO imiona(pozycja,imie) VALUES (74,'Witold');
INSERT INTO imiona(pozycja,imie) VALUES (75,'Bogumiła');
INSERT INTO imiona(pozycja,imie) VALUES (75,'Sylwester');
INSERT INTO imiona(pozycja,imie) VALUES (76,'Angelika');
INSERT INTO imiona(pozycja,imie) VALUES (76,'Hubert');
INSERT INTO imiona(pozycja,imie) VALUES (77,'Sabina');
INSERT INTO imiona(pozycja,imie) VALUES (77,'Mikołaj');
INSERT INTO imiona(pozycja,imie) VALUES (78,'Daria');
INSERT INTO imiona(pozycja,imie) VALUES (78,'Filip');
INSERT INTO imiona(pozycja,imie) VALUES (79,'Aniela');
INSERT INTO imiona(pozycja,imie) VALUES (79,'Wiktor');
INSERT INTO imiona(pozycja,imie) VALUES (80,'Bogusława');
INSERT INTO imiona(pozycja,imie) VALUES (80,'Bronisław');
INSERT INTO imiona(pozycja,imie) VALUES (81,'Leokadia');
INSERT INTO imiona(pozycja,imie) VALUES (81,'Wacław');
INSERT INTO imiona(pozycja,imie) VALUES (82,'Bronisława');
INSERT INTO imiona(pozycja,imie) VALUES (82,'Bolesław');
INSERT INTO imiona(pozycja,imie) VALUES (83,'Ilona');
INSERT INTO imiona(pozycja,imie) VALUES (83,'Cezary');
INSERT INTO imiona(pozycja,imie) VALUES (84,'Cecylia');
INSERT INTO imiona(pozycja,imie) VALUES (84,'Norbert');
INSERT INTO imiona(pozycja,imie) VALUES (85,'Marlena');
INSERT INTO imiona(pozycja,imie) VALUES (85,'Lech');
INSERT INTO imiona(pozycja,imie) VALUES (86,'Olga');
INSERT INTO imiona(pozycja,imie) VALUES (86,'Oskar');
INSERT INTO imiona(pozycja,imie) VALUES (87,'Sandra');
INSERT INTO imiona(pozycja,imie) VALUES (87,'Edmund');
INSERT INTO imiona(pozycja,imie) VALUES (88,'Łucja');
INSERT INTO imiona(pozycja,imie) VALUES (88,'Igor');
INSERT INTO imiona(pozycja,imie) VALUES (89,'Anita');
INSERT INTO imiona(pozycja,imie) VALUES (89,'Miłosz');
INSERT INTO imiona(pozycja,imie) VALUES (90,'Eugenia');
INSERT INTO imiona(pozycja,imie) VALUES (90,'Emil');
INSERT INTO imiona(pozycja,imie) VALUES (91,'Maja');
INSERT INTO imiona(pozycja,imie) VALUES (91,'Maksymilian');
INSERT INTO imiona(pozycja,imie) VALUES (92,'Milena');
INSERT INTO imiona(pozycja,imie) VALUES (92,'Leon');
INSERT INTO imiona(pozycja,imie) VALUES (93,'Zdzisława');
INSERT INTO imiona(pozycja,imie) VALUES (93,'Julian');
INSERT INTO imiona(pozycja,imie) VALUES (94,'Wioleta');
INSERT INTO imiona(pozycja,imie) VALUES (94,'Bernard');
INSERT INTO imiona(pozycja,imie) VALUES (95,'Daniela');
INSERT INTO imiona(pozycja,imie) VALUES (95,'Lucjan');
INSERT INTO imiona(pozycja,imie) VALUES (96,'Michalina');
INSERT INTO imiona(pozycja,imie) VALUES (96,'Błażej');
INSERT INTO imiona(pozycja,imie) VALUES (97,'Amelia');
INSERT INTO imiona(pozycja,imie) VALUES (97,'Romuald');
INSERT INTO imiona(pozycja,imie) VALUES (98,'Antonina');
INSERT INTO imiona(pozycja,imie) VALUES (98,'Eryk');
INSERT INTO imiona(pozycja,imie) VALUES (99,'Dagmara');
INSERT INTO imiona(pozycja,imie) VALUES (99,'Ludwik');
INSERT INTO imiona(pozycja,imie) VALUES (100,'Żaneta');
INSERT INTO imiona(pozycja,imie) VALUES (100,'Alfred');
INSERT INTO imiona(pozycja,imie) VALUES (101,'Nikola');
INSERT INTO imiona(pozycja,imie) VALUES (101,'Remigiusz');
INSERT INTO imiona(pozycja,imie) VALUES (102,'Adrianna');
INSERT INTO imiona(pozycja,imie) VALUES (102,'Szczepan');
INSERT INTO imiona(pozycja,imie) VALUES (103,'Bernadeta');
INSERT INTO imiona(pozycja,imie) VALUES (103,'Feliks');
INSERT INTO imiona(pozycja,imie) VALUES (104,'Karina');
INSERT INTO imiona(pozycja,imie) VALUES (104,'Gabriel');
INSERT INTO imiona(pozycja,imie) VALUES (105,'Gertruda');
INSERT INTO imiona(pozycja,imie) VALUES (105,'Marcel');
INSERT INTO imiona(pozycja,imie) VALUES (106,'Rozalia');
INSERT INTO imiona(pozycja,imie) VALUES (106,'Alojzy');
INSERT INTO imiona(pozycja,imie) VALUES (107,'Roksana');
INSERT INTO imiona(pozycja,imie) VALUES (107,'Bogumił');
INSERT INTO imiona(pozycja,imie) VALUES (108,'Aldona');
INSERT INTO imiona(pozycja,imie) VALUES (108,'Lesław');
INSERT INTO imiona(pozycja,imie) VALUES (109,'Franciszka');
INSERT INTO imiona(pozycja,imie) VALUES (109,'Ignacy');
INSERT INTO imiona(pozycja,imie) VALUES (110,'Malwina');
INSERT INTO imiona(pozycja,imie) VALUES (110,'Gerard');
INSERT INTO imiona(pozycja,imie) VALUES (111,'Mieczysława');
INSERT INTO imiona(pozycja,imie) VALUES (111,'Albert');
INSERT INTO imiona(pozycja,imie) VALUES (112,'Honorata');
INSERT INTO imiona(pozycja,imie) VALUES (112,'Seweryn');
INSERT INTO imiona(pozycja,imie) VALUES (113,'Celina');
INSERT INTO imiona(pozycja,imie) VALUES (113,'Alan');
INSERT INTO imiona(pozycja,imie) VALUES (114,'Kornelia');
INSERT INTO imiona(pozycja,imie) VALUES (114,'Oliwier');
INSERT INTO imiona(pozycja,imie) VALUES (115,'Róża');
INSERT INTO imiona(pozycja,imie) VALUES (115,'Nikodem');
INSERT INTO imiona(pozycja,imie) VALUES (116,'Violetta');
INSERT INTO imiona(pozycja,imie) VALUES (116,'Joachim');
INSERT INTO imiona(pozycja,imie) VALUES (117,'Julita');
INSERT INTO imiona(pozycja,imie) VALUES (117,'Ernest');
INSERT INTO imiona(pozycja,imie) VALUES (118,'Eliza');
INSERT INTO imiona(pozycja,imie) VALUES (118,'Benedykt');
INSERT INTO imiona(pozycja,imie) VALUES (119,'Jagoda');
INSERT INTO imiona(pozycja,imie) VALUES (119,'Fabian');
INSERT INTO imiona(pozycja,imie) VALUES (120,'Magda');
INSERT INTO imiona(pozycja,imie) VALUES (120,'Wincenty');
INSERT INTO imiona(pozycja,imie) VALUES (121,'Nina');
INSERT INTO imiona(pozycja,imie) VALUES (121,'Gracjan');
INSERT INTO imiona(pozycja,imie) VALUES (122,'Bożenna');
INSERT INTO imiona(pozycja,imie) VALUES (122,'Hieronim');
INSERT INTO imiona(pozycja,imie) VALUES (123,'Sara');
INSERT INTO imiona(pozycja,imie) VALUES (123,'Leonard');
INSERT INTO imiona(pozycja,imie) VALUES (124,'Alfreda');
INSERT INTO imiona(pozycja,imie) VALUES (124,'Rajmund');
INSERT INTO imiona(pozycja,imie) VALUES (125,'Adela');
INSERT INTO imiona(pozycja,imie) VALUES (125,'Jędrzej');
INSERT INTO imiona(pozycja,imie) VALUES (126,'Laura');
INSERT INTO imiona(pozycja,imie) VALUES (126,'Tobiasz');
INSERT INTO imiona(pozycja,imie) VALUES (127,'Brygida');
INSERT INTO imiona(pozycja,imie) VALUES (127,'Rudolf');
INSERT INTO imiona(pozycja,imie) VALUES (128,'Adriana');
INSERT INTO imiona(pozycja,imie) VALUES (128,'Adolf');
INSERT INTO imiona(pozycja,imie) VALUES (129,'Marcelina');
INSERT INTO imiona(pozycja,imie) VALUES (129,'Teodor');
INSERT INTO imiona(pozycja,imie) VALUES (130,'Wacława');
INSERT INTO imiona(pozycja,imie) VALUES (130,'Klaudiusz');
INSERT INTO imiona(pozycja,imie) VALUES (131,'Ludwika');
INSERT INTO imiona(pozycja,imie) VALUES (131,'Tymoteusz');
INSERT INTO imiona(pozycja,imie) VALUES (132,'Izabella');
INSERT INTO imiona(pozycja,imie) VALUES (132,'Walenty');
INSERT INTO imiona(pozycja,imie) VALUES (133,'Paula');
INSERT INTO imiona(pozycja,imie) VALUES (133,'Zygfryd');
INSERT INTO imiona(pozycja,imie) VALUES (134,'Marzanna');
INSERT INTO imiona(pozycja,imie) VALUES (134,'Juliusz');
INSERT INTO imiona(pozycja,imie) VALUES (135,'Elwira');
INSERT INTO imiona(pozycja,imie) VALUES (135,'Olaf');
INSERT INTO imiona(pozycja,imie) VALUES (136,'Anastazja');
INSERT INTO imiona(pozycja,imie) VALUES (136,'Alfons');
INSERT INTO imiona(pozycja,imie) VALUES (137,'Eleonora');
INSERT INTO imiona(pozycja,imie) VALUES (137,'Kajetan');
INSERT INTO imiona(pozycja,imie) VALUES (138,'Pelagia');
INSERT INTO imiona(pozycja,imie) VALUES (138,'Augustyn');
INSERT INTO imiona(pozycja,imie) VALUES (139,'Arleta');
INSERT INTO imiona(pozycja,imie) VALUES (139,'Florian');
INSERT INTO imiona(pozycja,imie) VALUES (140,'Apolonia');
INSERT INTO imiona(pozycja,imie) VALUES (140,'Konstanty');
INSERT INTO imiona(pozycja,imie) VALUES (141,'Diana');
INSERT INTO imiona(pozycja,imie) VALUES (141,'Leopold');
INSERT INTO imiona(pozycja,imie) VALUES (142,'Andżelika');
INSERT INTO imiona(pozycja,imie) VALUES (142,'Albin');
INSERT INTO imiona(pozycja,imie) VALUES (143,'Iga');
INSERT INTO imiona(pozycja,imie) VALUES (143,'Kornel');
INSERT INTO imiona(pozycja,imie) VALUES (144,'Aurelia');
INSERT INTO imiona(pozycja,imie) VALUES (144,'Erwin');
INSERT INTO imiona(pozycja,imie) VALUES (145,'Julianna');
INSERT INTO imiona(pozycja,imie) VALUES (145,'Bohdan');
INSERT INTO imiona(pozycja,imie) VALUES (146,'Zenona');
INSERT INTO imiona(pozycja,imie) VALUES (146,'Fryderyk');
INSERT INTO imiona(pozycja,imie) VALUES (147,'Romana');
INSERT INTO imiona(pozycja,imie) VALUES (147,'Marceli');
INSERT INTO imiona(pozycja,imie) VALUES (148,'Felicja');
INSERT INTO imiona(pozycja,imie) VALUES (148,'Aleksy');
INSERT INTO imiona(pozycja,imie) VALUES (149,'Waleria');
INSERT INTO imiona(pozycja,imie) VALUES (149,'Brunon');
INSERT INTO imiona(pozycja,imie) VALUES (150,'Zenobia');
INSERT INTO imiona(pozycja,imie) VALUES (150,'Ariel');
INSERT INTO imiona(pozycja,imie) VALUES (151,'Walentyna');
INSERT INTO imiona(pozycja,imie) VALUES (151,'Denis');
INSERT INTO imiona(pozycja,imie) VALUES (152,'Sonia');
INSERT INTO imiona(pozycja,imie) VALUES (152,'Kuba');
INSERT INTO imiona(pozycja,imie) VALUES (153,'Klara');
INSERT INTO imiona(pozycja,imie) VALUES (153,'Teofil');
INSERT INTO imiona(pozycja,imie) VALUES (154,'Liliana');
INSERT INTO imiona(pozycja,imie) VALUES (154,'Gustaw');
INSERT INTO imiona(pozycja,imie) VALUES (155,'Feliksa');
INSERT INTO imiona(pozycja,imie) VALUES (155,'Cyprian');
INSERT INTO imiona(pozycja,imie) VALUES (156,'Hildegarda');
INSERT INTO imiona(pozycja,imie) VALUES (156,'Sergiusz');
INSERT INTO imiona(pozycja,imie) VALUES (157,'Romualda');
INSERT INTO imiona(pozycja,imie) VALUES (157,'Borys');
INSERT INTO imiona(pozycja,imie) VALUES (158,'Marzenna');
INSERT INTO imiona(pozycja,imie) VALUES (158,'Walerian');
INSERT INTO imiona(pozycja,imie) VALUES (159,'Judyta');
INSERT INTO imiona(pozycja,imie) VALUES (159,'Roland');
INSERT INTO imiona(pozycja,imie) VALUES (160,'Teodozja');
INSERT INTO imiona(pozycja,imie) VALUES (160,'Emilian');
INSERT INTO imiona(pozycja,imie) VALUES (161,'Lena');
INSERT INTO imiona(pozycja,imie) VALUES (161,'Herbert');
INSERT INTO imiona(pozycja,imie) VALUES (162,'Marika');
INSERT INTO imiona(pozycja,imie) VALUES (162,'Dorian');
INSERT INTO imiona(pozycja,imie) VALUES (163,'Luiza');
INSERT INTO imiona(pozycja,imie) VALUES (163,'Martin');
INSERT INTO imiona(pozycja,imie) VALUES (164,'Kaja');
INSERT INTO imiona(pozycja,imie) VALUES (164,'Wilhelm');
INSERT INTO imiona(pozycja,imie) VALUES (165,'Lilianna');
INSERT INTO imiona(pozycja,imie) VALUES (165,'Anatol');
INSERT INTO imiona(pozycja,imie) VALUES (166,'Teodora');
INSERT INTO imiona(pozycja,imie) VALUES (166,'Amadeusz');
INSERT INTO imiona(pozycja,imie) VALUES (167,'Bernadetta');
INSERT INTO imiona(pozycja,imie) VALUES (167,'Edwin');
INSERT INTO imiona(pozycja,imie) VALUES (168,'Donata');
INSERT INTO imiona(pozycja,imie) VALUES (168,'Beniamin');
INSERT INTO imiona(pozycja,imie) VALUES (169,'Ludmiła');
INSERT INTO imiona(pozycja,imie) VALUES (169,'Ferdynand');
INSERT INTO imiona(pozycja,imie) VALUES (170,'Matylda');
INSERT INTO imiona(pozycja,imie) VALUES (170,'Arnold');
INSERT INTO imiona(pozycja,imie) VALUES (171,'Jowita');
INSERT INTO imiona(pozycja,imie) VALUES (171,'Lechosław');
INSERT INTO imiona(pozycja,imie) VALUES (172,'Longina');
INSERT INTO imiona(pozycja,imie) VALUES (172,'Longin');
INSERT INTO imiona(pozycja,imie) VALUES (173,'Otylia');
INSERT INTO imiona(pozycja,imie) VALUES (173,'Klemens');
INSERT INTO imiona(pozycja,imie) VALUES (174,'Anetta');
INSERT INTO imiona(pozycja,imie) VALUES (174,'Olgierd');
INSERT INTO imiona(pozycja,imie) VALUES (175,'Nadia');
INSERT INTO imiona(pozycja,imie) VALUES (175,'Kewin');
UPDATE imiona SET plec='K' WHERE idi%2=1;
UPDATE imiona SET plec='M' WHERE idi%2=0;
COMMIT;

DROP TABLE IF EXISTS nazwiska;
CREATE TABLE IF NOT EXISTS nazwiska(
 idn INTEGER PRIMARY KEY,
 nazwisko TEXT,
 pozycja INT,
 liczba INT,
 plec CHAR(1));
BEGIN TRANSACTION;
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowak', 1, 139072, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowak', 1, 138119, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kowalska', 2, 89429, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kowalski', 2, 88674, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wiśniewska', 3, 70244, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wiśniewski', 3, 69558, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wójcik', 4, 63538, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wójcik', 4, 62987, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kowalczyk', 5, 61958, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kowalczyk', 5, 61880, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kamińska', 6, 60846, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kamiński', 6, 59863, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Lewandowska', 7, 59773, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Lewandowski', 7, 58618, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Dąbrowska', 8, 59529, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Dąbrowski', 8, 57877, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zielińska', 9, 58771, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zieliński', 9, 57605, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szymańska', 10, 57619, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szymański', 10, 56456, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Woźniak', 11, 56440, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Woźniak', 11, 56365, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kozłowska', 12, 48911, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kozłowski', 12, 48163, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jankowska', 13, 44103, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jankowski', 13, 43466, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wojciechowska', 14, 42828, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mazur', 14, 42530, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kwiatkowska', 15, 42798, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wojciechowski', 15, 41864, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mazur', 16, 42623, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kwiatkowski', 16, 41797, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krawczyk', 17, 40878, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krawczyk', 17, 40572, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Piotrowska', 18, 39857, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaczmarek', 18, 39505, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaczmarek', 19, 39641, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Piotrowski', 19, 38770, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Grabowska', 20, 37693, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Grabowski', 20, 36847, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pawłowska', 21, 35781, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zając', 21, 35362, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Michalska', 22, 35587, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pawłowski', 22, 35143, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zając', 23, 34628, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Michalski', 23, 34592, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Król', 24, 34496, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Król', 24, 34330, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowakowska', 25, 34076, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowakowski', 25, 33323, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wieczorek', 26, 32857, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wieczorek', 26, 32278, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jabłońska', 27, 32502, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wróbel', 27, 32166, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Majewska', 28, 31912, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jabłoński', 28, 31687, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Adamczyk', 29, 31890, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Dudek', 29, 31542, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wróbel', 30, 31692, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Adamczyk', 30, 31511, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowicka', 31, 31480, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Majewski', 31, 31012, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Dudek', 32, 31120, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Nowicki', 32, 30455, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Olszewska', 33, 30794, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Olszewski', 33, 30257, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jaworska', 34, 30619, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Stępień', 34, 30073, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Malinowska', 35, 30100, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jaworski', 35, 29823, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Stępień', 36, 29827, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Malinowski', 36, 29743, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Górska', 37, 29337, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pawlak', 37, 29063, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pawlak', 38, 28957, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Górski', 38, 28379, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Witkowska', 39, 28915, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Witkowski', 39, 28124, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Walczak', 40, 28253, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Walczak', 40, 28064, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Rutkowska', 41, 28158, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sikora', 41, 27996, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sikora', 42, 27970, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Rutkowski', 42, 27588, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Michalak', 43, 27351, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Baran', 43, 27397, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Ostrowska', 44, 27159, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Michalak', 44, 27078, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szewczyk', 45, 27156, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szewczyk', 45, 26858, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Baran', 46, 26694, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Ostrowski', 46, 26298, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Tomaszewska', 47, 26033, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Tomaszewski', 47, 25279, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pietrzak', 48, 25369, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Pietrzak', 48, 24856, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jasińska', 49, 24933, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Duda', 49, 24806, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wróblewska', 50, 24902, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zalewski', 50, 24691, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zalewska', 51, 24859, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wróblewski', 51, 24409, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Marciniak', 52, 24688, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jasiński', 52, 24202, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zawadzka', 53, 24458, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Marciniak', 53, 24146, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jakubowska', 54, 24419, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Bąk', 54, 23885, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Duda', 55, 24279, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zawadzki', 55, 23779, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sadowska', 56, 24105, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sadowski', 56, 23774, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Bąk', 57, 23109, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Jakubowski', 57, 23686, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Włodarczyk', 58, 23026, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wilk', 58, 22618, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Chmielewska', 59, 22847, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Włodarczyk', 59, 22513, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Borkowska', 60, 22843, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Chmielewski', 60, 22503, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sokołowska', 61, 22459, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Borkowski', 61, 22045, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wilk', 62, 22351, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sokołowski', 62, 21528, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sawicka', 63, 21915, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szczepański', 63, 21447, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szczepańska', 64, 21883, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sawicki', 64, 21373, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kucharska', 65, 21318, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Lis', 65, 21204, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Lis', 66, 21074, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kucharski', 66, 20972, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Maciejewska', 67, 20887, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mazurek', 67, 20416, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Czarnecka', 68, 20832, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kubiak', 68, 20354, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kalinowska', 69, 20726, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kalinowski', 69, 20250, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kubiak', 70, 20722, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wysocki', 70, 20230, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wysocka', 71, 20680, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Maciejewski', 71, 20195, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mazurek', 72, 20539, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Czarnecki', 72, 20181, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Urbańska', 73, 19769, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kołodziej', 73, 19439, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kołodziej', 74, 19690, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Urbański', 74, 19302, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaźmierczak', 75, 19229, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaźmierczak', 75, 19206, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sobczak', 76, 18295, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sobczak', 76, 18379, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sikorska', 77, 18253, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Konieczny', 77, 18153, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Głowacka', 78, 18223, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Głowacki', 78, 17850, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krajewska', 79, 18125, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zakrzewski', 79, 17666, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Zakrzewska', 80, 18091, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krupa', 80, 17652, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Adamska', 81, 17982, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wasilewski', 81, 17606, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Wasilewska', 82, 17821, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krajewski', 82, 17525, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Gajewska', 83, 17619, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Adamski', 83, 17440, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Laskowska', 84, 17611, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Sikorski', 84, 17339, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Krupa', 85, 17569, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mróz', 85, 17214, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Ziółkowska', 86, 17522, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Laskowski', 86, 17201, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szulc', 87, 17344, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Gajewski', 87, 17193, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Czerwińska', 88, 17321, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Ziółkowski', 88, 17167, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Makowska', 89, 17271, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szulc', 89, 17137, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Brzezińska', 90, 17129, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Makowski', 90, 17024, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Przybylska', 91, 17109, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Czerwiński', 91, 16841, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szymczak', 92, 17058, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Baranowski', 92, 16834, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Baranowska', 93, 17046, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Szymczak', 93, 16768, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Mróz', 94, 16998, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Brzeziński', 94, 16730, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Błaszczyk', 95, 16918, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaczmarczyk', 95, 16696, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Borowska', 96, 16883, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Przybylski', 96, 16696, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Andrzejewska', 97, 16811, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Cieślak', 97, 16540, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Górecka', 98, 16660, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Borowski', 98, 16528, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Cieślak', 99, 16627, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Błaszczyk', 99, 16524, 'M');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Kaczmarczyk', 100, 16599, 'K');
INSERT INTO nazwiska(nazwisko, pozycja, liczba, plec) VALUES('Andrzejewski', 100, 16509, 'M');
COMMIT;

DROP TABLE IF EXISTS imiona14;
CREATE TABLE IF NOT EXISTS imiona14(
 idi14 INTEGER PRIMARY KEY,
 imie TEXT UNIQUE,
 pozycja INT,
 liczba INT,
 plec CHAR(1));
BEGIN TRANSACTION;
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Lena', 1, 9642, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jakub', 1, 9382, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Zuzanna', 2, 8856, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kacper', 2, 7232, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Julia', 3, 8572, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Antoni', 3, 7143, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Maja', 4, 8055, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Filip', 4, 6903, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Zofia', 5, 6733, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jan', 5, 6817, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Hanna', 6, 6407, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Szymon', 6, 6112, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Aleksandra', 7, 5935, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Franciszek', 7, 5139, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Amelia', 8, 5586, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Michał', 8, 5004, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Natalia', 9, 5205, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Wojciech', 9, 4959, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Wiktoria', 10, 5149, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Aleksander', 10, 4896, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Alicja', 11, 4932, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Mikołaj', 11, 4787, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Oliwia', 12, 4807, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Adam', 12, 4681, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nikola', 13, 3969, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Piotr', 13, 4149, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Maria', 14, 3719, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Mateusz', 14, 3978, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Emilia', 15, 3604, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Bartosz', 15, 3939, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Anna', 16, 3265, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Igor', 16, 3795, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nadia', 17, 3103, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Wiktor', 17, 3755, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Antonina', 18, 2953, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marcel', 18, 3736, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Gabriela', 19, 2808, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dawid', 19, 3021, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Martyna', 20, 2719, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Stanisław', 20, 2798, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Liliana', 21, 2543, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Miłosz', 21, 2713, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Milena', 22, 2463, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Maksymilian', 22, 2712, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Laura', 23, 2261, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Karol', 23, 2684, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Pola', 24, 2224, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Alan', 24, 2665, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Magdalena', 25, 2175, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Oliwier', 25, 2556, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Karolina', 26, 2004, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Oskar', 26, 2549, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kornelia', 27, 1942, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Maciej', 27, 2514, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Weronika', 28, 1855, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Tomasz', 28, 2401, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Agata', 29, 1812, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dominik', 29, 2309, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Iga', 30, 1729, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nikodem', 30, 2293, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jagoda', 31, 1572, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Krzysztof', 31, 2160, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nina', 32, 1471, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Paweł', 32, 2103, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Barbara', 33, 1432, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Leon', 33, 2051, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Michalina', 34, 1428, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Hubert', 34, 1951, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kinga', 35, 1344, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kamil', 35, 1884, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Helena', 36, 1334, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Natan', 36, 1852, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Paulina', 37, 1332, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Fabian', 37, 1815, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marcelina', 38, 1216, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Patryk', 38, 1669, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marta', 39, 1150, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Bartłomiej', 39, 1634, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Patrycja', 40, 1133, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Julian', 40, 1573, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Małgorzata', 41, 1106, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Tymon', 41, 1535, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Katarzyna', 42, 1095, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Tymoteusz', 42, 1531, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Klaudia', 43, 1021, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ksawery', 43, 1434, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Łucja', 44, 952, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ignacy', 44, 1408, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Joanna', 45, 949, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Sebastian', 45, 1403, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Blanka', 46, 928, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Gabriel', 46, 1392, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kaja', 47, 918, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Krystian', 47, 1126, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Izabela', 48, 875, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Adrian', 48, 1103, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dominika', 49, 866, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Łukasz', 49, 935, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ewa', 50, 755, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marcin', 50, 910, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Klara', 51, 716, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Błażej', 51, 904, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Anastazja', 52, 682, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kajetan', 52, 857, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nela', 53, 660, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Borys', 53, 799, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Lilianna', 54, 649, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Artur', 54, 782, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Sara', 55, 625, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Daniel', 55, 746, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Olga', 56, 623, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Damian', 56, 711, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kalina', 57, 611, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Eryk', 57, 709, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kamila', 58, 608, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Grzegorz', 58, 703, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Daria', 59, 562, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kuba', 59, 680, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Malwina', 60, 532, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Olaf', 60, 635, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Sandra', 61, 532, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Rafał', 61, 616, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Matylda', 62, 525, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Konrad', 62, 608, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Aniela', 63, 515, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Przemysław', 63, 579, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Adrianna', 64, 501, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nataniel', 64, 532, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Urszula', 65, 501, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Radosław', 65, 519, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Eliza', 66, 493, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Tobiasz', 66, 501, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Roksana', 67, 457, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Bruno', 67, 488, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Natasza', 68, 426, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Cezary', 68, 474, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dorota', 69, 406, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Olivier', 69, 449, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Róża', 70, 401, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marek', 70, 404, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Justyna', 71, 387, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Robert', 71, 400, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Lidia', 72, 385, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Emil', 72, 397, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marianna', 73, 381, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Witold', 73, 384, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marika', 74, 365, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kornel', 74, 368, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Liwia', 75, 364, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Alex', 75, 364, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Agnieszka', 76, 349, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Aleks', 76, 361, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Karina', 77, 345, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Tadeusz', 77, 358, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Rozalia', 78, 332, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Gracjan', 78, 353, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Nicola', 79, 304, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jerzy', 79, 348, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Monika', 80, 299, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Andrzej', 80, 305, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Vanessa', 81, 283, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Arkadiusz', 81, 282, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Bianka', 82, 282, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Milan', 82, 253, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Aurelia', 83, 269, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jacek', 83, 241, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ada', 84, 257, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Mieszko', 84, 241, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Marlena', 85, 238, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Norbert', 85, 241, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dagmara', 86, 220, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Dorian', 86, 238, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Emma', 87, 209, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Brajan', 87, 236, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Inga', 88, 206, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Stefan', 88, 236, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Elena', 89, 189, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Iwo', 89, 233, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Olivia', 90, 189, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Gustaw', 90, 226, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Julita', 91, 185, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Konstanty', 91, 219, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Diana', 92, 176, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Leonard', 92, 219, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ewelina', 93, 174, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Alexander', 93, 214, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Anita', 94, 170, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Seweryn', 94, 214, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Victoria', 95, 169, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Juliusz', 95, 206, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Mia', 96, 164, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Ryszard', 96, 205, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Apolonia', 97, 151, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Józef', 97, 187, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Elżbieta', 98, 147, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Kazimierz', 98, 184, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Sonia', 99, 145, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Jędrzej', 99, 170, 'M');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Melania', 100, 144, 'K');
INSERT INTO imiona14(imie, pozycja, liczba, plec) VALUES('Cyprian', 100, 166, 'M');
COMMIT;
